import type { Theme } from '../types/index';

const baseTheme = {
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 2,
    sm: 4,
    md: 8,
    lg: 12,
    full: 9999,
  },
};

export const lightTheme: Theme = {
  colors: {
    primary: '#007AFF',
    secondary: '#5AC8FA',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#000000',
    textSecondary: '#666666',
    textTertiary: '#999999',
    border: '#CCCCCC',
    borderLight: '#E8E8E8',
    error: '#FF3B30',
    success: '#34C759',
    warning: '#FF9500',
    info: '#5AC8FA',
    transparent: 'transparent',
    white: '#FFFFFF',
    black: '#000000',
    disabled: '#D0D0D0',
  },
  typography: {
    h1: { fontSize: 48, fontWeight: '700', lineHeight: 56 },
    h2: { fontSize: 40, fontWeight: '700', lineHeight: 48 },
    h3: { fontSize: 34, fontWeight: '700', lineHeight: 41 },
    h4: { fontSize: 28, fontWeight: '700', lineHeight: 34 },
    h5: { fontSize: 22, fontWeight: '600', lineHeight: 28 },
    h6: { fontSize: 18, fontWeight: '600', lineHeight: 24 },
    body1: { fontSize: 16, fontWeight: '400', lineHeight: 24 },
    body2: { fontSize: 15, fontWeight: '400', lineHeight: 22 },
    body3: { fontSize: 14, fontWeight: '400', lineHeight: 20 },
    body4: { fontSize: 13, fontWeight: '400', lineHeight: 18 },
    body5: { fontSize: 12, fontWeight: '400', lineHeight: 16 },
    body6: { fontSize: 11, fontWeight: '400', lineHeight: 15 },
    subtitle1: { fontSize: 14, fontWeight: '600', lineHeight: 20 },
    subtitle2: { fontSize: 12, fontWeight: '600', lineHeight: 16 },
    caption: { fontSize: 12, fontWeight: '400', lineHeight: 16 },
    overline: { fontSize: 10, fontWeight: '600', lineHeight: 14 },
  },
  ...baseTheme,
  shadows: {
    light: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    heavy: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};

export const darkTheme: Theme = {
  colors: {
    primary: '#0A84FF',
    secondary: '#30B0C5',
    background: '#1C1C1E',
    surface: '#2C2C2E',
    text: '#FFFFFF',
    textSecondary: '#A0A0A0',
    textTertiary: '#808080',
    border: '#454546',
    borderLight: '#3A3A3C',
    error: '#FF453A',
    success: '#30C759',
    warning: '#FF9500',
    info: '#30B0C5',
    transparent: 'transparent',
    white: '#FFFFFF',
    black: '#000000',
    disabled: '#636366',
  },
  typography: lightTheme.typography,
  ...baseTheme,
  shadows: {
    light: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    },
    heavy: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.5,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};
